export const ERROR_CODES = {
  // Auth
  AUTH: {
    INVALID_CREDENTIALS: 'AUTH_001',
    TOKEN_EXPIRED: 'AUTH_002',
    UNAUTHORIZED: 'AUTH_003',
    REFRESH_TOKEN_INVALID: 'AUTH_004',
    ACCOUNT_SUSPENDED: 'AUTH_005',
    ACCOUNT_PENDING: 'AUTH_006',
    OTP_INVALID: 'AUTH_007',
    OTP_EXPIRED: 'AUTH_008',
    OTP_ATTEMPTS_EXCEEDED: 'AUTH_009',
    RESET_TOKEN_INVALID: 'AUTH_010',
  },

  // User
  USER: {
    NOT_FOUND: 'USER_001',
    EMAIL_EXISTS: 'USER_002',
    FORBIDDEN: 'USER_003',
    INVALID_STATE: 'USER_004',
    SELF_MODIFY: 'USER_005',
    INVALID_ROLE: 'USER_006',
  },

  // Store
  STORE: {
    NOT_FOUND: 'STORE_001',
    DUPLICATE: 'STORE_002',
    INVALID_PROVINCE: 'STORE_003',
    DOCUMENT_NOT_FOUND: 'STORE_004',
    INVALID_OWNER: 'STORE_005',
    PHOTO_NOT_FOUND: 'STORE_006',
    INVALID_REVENUE_RANGE: 'STORE_007',
    DUPLICATE_CODE: 'STORE_008',
    INVALID_STORE_TYPE: 'STORE_009',
    IN_USE: 'STORE_010',
  },

  // Assessment
  ASSESS: {
    NOT_FOUND: 'ASSESS_001',
    DUPLICATE: 'ASSESS_002',
    INVALID_STATE: 'ASSESS_003',
    SUBMITTED: 'ASSESS_004',
    NOT_ALL_SCORED: 'ASSESS_005',
    SCORE_OUT_OF_RANGE: 'ASSESS_006',
    QUESTION_NOT_FOUND: 'ASSESS_007',
  },

  // Pitching (judge scoring forms)
  PITCH: {
    NOT_FOUND: 'PITCH_001',
    DUPLICATE: 'PITCH_002',
    INVALID_STATE: 'PITCH_003',
    // Retired: a submitted form stays editable. Reserved so the code is never reused.
    SUBMITTED: 'PITCH_004',
    NOT_ALL_SCORED: 'PITCH_005',
    SCORE_OUT_OF_RANGE: 'PITCH_006',
    CRITERION_NOT_FOUND: 'PITCH_007',
    MISSING_MINIMUM_INPUTS: 'PITCH_008',
    INVALID_RECOMMENDATION: 'PITCH_009',
  },

  // News / announcements
  NEWS: {
    NOT_FOUND: 'NEWS_001',
  },

  // Reports
  RPT: {
    NOT_FOUND: 'RPT_001',
    NO_ASSESSMENT: 'RPT_002',
  },

  // Validation
  VALID: {
    BAD_REQUEST: 'VALID_001',
    VALIDATION_FAILED: 'VALID_002',
  },

  // Permission
  PERM: {
    FORBIDDEN: 'PERM_001',
  },

  // File upload
  FILE: {
    INVALID_TYPE: 'FILE_001',
    TOO_LARGE: 'FILE_002',
    NOT_FOUND: 'FILE_003',
  },

  // Database
  DB: {
    DUPLICATE: 'DB_001',
    NOT_FOUND: 'DB_002',
    FOREIGN_KEY: 'DB_003',
    INVALID_DATA: 'DB_004',
    NULL_CONSTRAINT: 'DB_005',
    GENERIC: 'DB_999',
  },

  // System
  SYS: {
    UNEXPECTED: 'SYS_001',
  },
} as const;
