export { ERROR_CODES } from './error-codes.const';
export { STORE_TARGET_TOTAL } from './store.const';
export {
  FILE_MAX_SIZE_BYTES,
  FILE_MAX_SIZE_MB,
  PHOTO_MIME_REGEX,
  STORE_DOCUMENT_MIME_REGEX,
  ASSESSMENT_EVIDENCE_MIME_REGEX,
  PHOTO_ALLOWED_EXTENSIONS,
  STORE_DOCUMENT_ALLOWED_EXTENSIONS,
  ASSESSMENT_EVIDENCE_ALLOWED_EXTENSIONS,
} from './file-upload.const';
